export const GET_ERRORS = "GET_ERRORS"
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER_PROFILE = "SET_PROFILE"
export const GET_CURRENT_PROFILE = "GET_CURRENT_PROFILE"
export const LOAD_PROFILE = "LOAD_PROFILE"
